esphome:
  name: t_embed
  includes:
    - custom_ble_list.h
  on_boot:
    priority: -100
    then:
      - script.execute: startup_sequence

esp32:
  board: esp32-s3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:
logger:

esp32_ble_tracker:

font:
  - file: "gfonts://Roboto"
    id: font
    size: 18

globals:
  - id: menu_page
    type: int
    restore_value: no
    initial_value: '0'   # 0 = menu, 1 = BLE page

# --- Settings (Persistent) ---
switch:
  - platform: template
    name: "Sound On/Off"
    id: sound_on_off
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config

number:
  - platform: template
    name: "FrontLawn Delay"
    id: frontlawn_delay
    min_value: 0
    max_value: 72
    step: 1
    initial_value: 0
    unit_of_measurement: h
    restore_value: true
    optimistic: true
  - platform: template
    name: "BackLawn Delay"
    id: backlawn_delay
    min_value: 0
    max_value: 72
    step: 1
    initial_value: 0
    unit_of_measurement: h
    restore_value: true
    optimistic: true
  - platform: template
    name: "Volume"
    id: volume_setting
    min_value: 0
    max_value: 100
    step: 1
    initial_value: 50
    restore_value: true
    optimistic: true

# --- Buzzer/Speaker ---
output:
  - platform: ledc
    pin: GPIO7  # Speaker Pin per your pinout image
    id: speaker_out

buzzer:
  - id: beeper
    output: speaker_out

light:
  - platform: apa102
    id: ring_leds
    num_leds: 7
    data_pin: GPIO42
    clock_pin: GPIO45
    rgb_order: BGR
    name: "Ring LEDs"
    restore_mode: ALWAYS_OFF

script:
  - id: startup_sequence
    mode: queued
    then:
      - lambda: |-
          // ---- CONNECTING TO WIFI: GREEN ----
          id(st7789v_display).fill(COLOR_BLACK);
          id(st7789v_display).printf(10, 80, id(font), COLOR_GREEN, "Connecting to WiFi...");
          id(st7789v_display).update();

          for (int frame = 0; frame < 28; ++frame) {  // 4 rotations
            std::vector<Color> pixels(7, Color(0, 32, 0));  // dim green base
            int l = frame % 7;
            for (int offset = 0; offset < 4; ++offset) {
              int idxp = (l + offset) % 7;
              int idxn = (l - offset + 7) % 7;
              uint8_t intensity = 32 + offset * 32; // 32, 64, 96, 128
              pixels[idxp] = Color(0, intensity, 0);
              pixels[idxn] = Color(0, intensity, 0);
            }
            id(ring_leds).get_light(0)->call_set_leds_raw(pixels);
            id(ring_leds).update();
            delay(50);
          }

      - wait_until:
          condition:
            wifi.connected:
          timeout: 15s

      - lambda: |-
          // ---- SEARCHING FOR BLE DEVICES: BLUE ----
          id(st7789v_display).fill(COLOR_BLACK);
          id(st7789v_display).printf(10, 80, id(font), COLOR_BLUE, "Searching for BLE devices...");
          id(st7789v_display).update();

          for (int frame = 0; frame < 28; ++frame) {
            std::vector<Color> pixels(7, Color(0, 0, 32));  // dim blue base
            int l = frame % 7;
            for (int offset = 0; offset < 4; ++offset) {
              int idxp = (l + offset) % 7;
              int idxn = (l - offset + 7) % 7;
              uint8_t intensity = 32 + offset * 32; // 32, 64, 96, 128
              pixels[idxp] = Color(0, 0, intensity);
              pixels[idxn] = Color(0, 0, intensity);
            }
            id(ring_leds).get_light(0)->call_set_leds_raw(pixels);
            id(ring_leds).update();
            delay(50);
          }

      - lambda: |-
          // Clear LEDs after startup
          std::vector<Color> pixels(7, Color(0, 0, 0));
          id(ring_leds).get_light(0)->call_set_leds_raw(pixels);
          id(ring_leds).update();

display:
  - platform: st7789v
    id: st7789v_display
    cs_pin: GPIO10
    dc_pin: GPIO13
    reset_pin: GPIO9
    backlight_pin: GPIO15
    rotation: 90
    data_pins: [GPIO11]         # MOSI
    clk_pin: GPIO12             # SCLK
    lambda: |-
      if (id(menu_page) == 1) {
        id(custom_ble_list_display).draw(it);
      } else {
        it.printf(10, 10, id(font), "Press BLE in menu!");
      }

custom_component:
  - lambda: |-
      auto my_ble_list = new CustomBLEListDisplay(id(font));
      App.register_component(my_ble_list);
      id(custom_ble_list_display) = my_ble_list;
      register_ble_list_display(my_ble_list);

rotary_encoder:
  - id: encoder
    pin_a: GPIO2
    pin_b: GPIO1
    min_value: 0
    max_value: 50
    on_clockwise:
      then:
        - lambda: |-
            if (id(menu_page) == 1) {
              id(custom_ble_list_display)->scroll(+1);
            } else {
              display.menu_next;
            }
    on_anticlockwise:
      then:
        - lambda: |-
            if (id(menu_page) == 1) {
              id(custom_ble_list_display)->scroll(-1);
            } else {
              display.menu_previous;
            }

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    name: "Encoder Button"
    on_press:
      then:
        - if:
            condition:
              switch.is_on: sound_on_off
            then:
              - buzzer.beep:
                  id: beeper
                  frequency: 2000 Hz
                  time_on: 50ms
                  volume: !lambda 'return id(volume_setting).state / 100.0;'
        - lambda: |-
            if (id(menu_page) == 0 && display_menu.is_on_ble_menu()) {
              id(menu_page) = 1;    // Show BLE page
            } else if (id(menu_page) == 1) {
              id(menu_page) = 0;    // Go back to main menu
            } else {
              display.menu_select;
            }

button:
  - platform: template
    name: "FrontLawn Start"
    id: start_frontlawn
    on_press:
      then:
        - homeassistant.service:
            service: script.start_frontlawn
  - platform: template
    name: "BackLawn Start"
    id: start_backlawn
    on_press:
      then:
        - homeassistant.service:
            service: script.start_backlawn
  - platform: template
    name: "FrontLawn Delay"
    id: delay_frontlawn
    on_press:
      then:
        - homeassistant.service:
            service: script.delay_frontlawn
            data:
              hours: !lambda 'return id(frontlawn_delay).state;'
  - platform: template
    name: "BackLawn Delay"
    id: delay_backlawn
    on_press:
      then:
        - homeassistant.service:
            service: script.delay_backlawn
            data:
              hours: !lambda 'return id(backlawn_delay).state;'

display_menu:
  id: menu
  display_id: st7789v_display
  main_menu:
    - type: submenu
      text: "Settings"
      id: settings_menu
      submenu:
        - type: switch
          name: "Sound"
          id: sound_on_off
        - type: number
          name: "Volume"
          id: volume_setting
        - type: back
          text: "Back"
    - type: submenu
      text: "BLE"
      id: ble_menu
      submenu:
        - type: custom
          text: "Show Devices"
          on_enter:
            - lambda: |-
                id(menu_page) = 1;
        - type: back
          text: "Back"
    - type: submenu
      text: "Riego"
      id: riego_menu
      submenu:
        - type: submenu
          text: "FrontLawn"
          id: frontlawn_menu
          submenu:
            - type: button
              name: "Start"
              id: start_frontlawn
            - type: number
              name: "Delay"
              id: frontlawn_delay
            - type: button
              name: "Apply Delay"
              id: delay_frontlawn
            - type: back
              text: "Back"
        - type: submenu
          text: "BackLawn"
          id: backlawn_menu
          submenu:
            - type: button
              name: "Start"
              id: start_backlawn
            - type: number
              name: "Delay"
              id: backlawn_delay
            - type: button
              name: "Apply Delay"
              id: delay_backlawn
            - type: back
              text: "Back"
        - type: back
          text: "Back"
